<a href="https://colab.research.google.com/github/nandini-mazumdar/learning-spark-again/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
array_a = np.arange(5)
array_a

array([0, 1, 2, 3, 4])

In [ ]:
array_a.shape

(5,)

# Reshape

In [ ]:
array_b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
array_b = np.reshape(array_b, (2,4))
print(array_b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array_b.shape

(2, 4)

In [ ]:
array_c=array_b.reshape((2,4,1))
array_c

array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])

In [ ]:
array_c.ndim

3

###Flatten

In [ ]:
#flattening
array_flat = np.reshape(array_c,-1)
array_flat

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#flatten - copy
arr_1=array_c.flatten()
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8])

###Ravel

In [ ]:
#ravel - view
arr_2 = array_c.ravel()
arr_2

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr_1[0]=111
arr_2[0]=222

print(array_c)
print(arr_1)
print(arr_2)

[[[222]
  [  2]
  [  3]
  [  4]]

 [[  5]
  [  6]
  [  7]
  [  8]]]
[111   2   3   4   5   6   7   8]
[222   2   3   4   5   6   7   8]


# Change Type

In [ ]:
array_b = array_b.astype(np.float32)
print(array_b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


# Data Types

In [ ]:
 array_x = np.array([-1, 0, 1], dtype=np.uint16)
 print(array_x)

[65535     0     1]


# Indexing

In [ ]:
two_dim = np.arange(1,13).reshape((3,4))
two_dim

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
three_dim = np.arange(3*4*5).reshape((3,4,5))
three_dim

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
three_dim[-1,-1,-1]

59

In [ ]:
print(array_c[0])

[[222]
 [  2]
 [  3]
 [  4]]


In [ ]:
print(array_c[:,1])

[[2]
 [6]]


In [ ]:
print(array_c[0], array_c[:,-1])

[[222]
 [  2]
 [  3]
 [  4]] [[4]
 [8]]


In [ ]:
array_d = np.full((3,3), 5.8)
print(array_d)

[[5.8 5.8 5.8]
 [5.8 5.8 5.8]
 [5.8 5.8 5.8]]


In [ ]:
array_e = np.random.random(size=(4,3)).astype(np.float16)
print(array_e)
print(array_e.dtype)

[[0.7334 0.7163 0.8413]
 [0.2761 0.3843 0.431 ]
 [0.646  0.915  0.2   ]
 [0.6865 0.7314 0.5864]]
float16


# Advanced Indexing

In [ ]:
array_y = np.arange(1,26).reshape((5,5))
print(array_y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(array_y[:,2:4:1])

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [ ]:
# negative index
print(array_y[:,-2:-4:-1])

[[ 4  3]
 [ 9  8]
 [14 13]
 [19 18]
 [24 23]]


In [ ]:
# boolean index
divisible_by_3 = array_y % 3 == 0
print(divisible_by_3)

[[False False  True False False]
 [ True False False  True False]
 [False  True False False  True]
 [False False  True False False]
 [ True False False  True False]]


In [ ]:
print(array_y[divisible_by_3])

[ 3  6  9 12 15 18 21 24]


In [ ]:
# where
drop_incorrect = np.where(divisible_by_3, array_y, 0)
print(drop_incorrect)

[[ 0  0  3  0  0]
 [ 6  0  0  9  0]
 [ 0 12  0  0 15]
 [ 0  0 18  0  0]
 [21  0  0 24  0]]


In [ ]:
# multiple conditions - logical AND
# drop under 5 and over 15

drop_under_5_under_15 = np.logical_and(array_y > 5, array_y < 15)
print(np.where(drop_under_5_under_15, array_y, -1))

[[-1 -1 -1 -1 -1]
 [ 6  7  8  9 10]
 [11 12 13 14 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


In [ ]:
print(array_y[array_y % 2 == 0])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
# slice of a row
print(array_y[:,0:5:2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [ ]:
# reverse every row
print(array_y[:,len(array_y[0])-1::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


#Slicing

In [ ]:
one_dim=np.arange(10)
one_dim

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_dim[2:6]

array([2, 3, 4, 5])

In [ ]:
one_dim[::2]

array([0, 2, 4, 6, 8])

In [ ]:
two_dim[:,-2]

array([ 3,  7, 11])

In [ ]:
two_dim[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [ ]:
three_dim[:,-1:,:]

array([[[15, 16, 17, 18, 19]],

       [[35, 36, 37, 38, 39]],

       [[55, 56, 57, 58, 59]]])

In [ ]:
# Flip function

np.flip(one_dim)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
np.flip(two_dim,1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
np.flip(three_dim,1)

array([[[15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4]],

       [[35, 36, 37, 38, 39],
        [30, 31, 32, 33, 34],
        [25, 26, 27, 28, 29],
        [20, 21, 22, 23, 24]],

       [[55, 56, 57, 58, 59],
        [50, 51, 52, 53, 54],
        [45, 46, 47, 48, 49],
        [40, 41, 42, 43, 44]]])

In [ ]:
np.flip(three_dim,2)

array([[[ 4,  3,  2,  1,  0],
        [ 9,  8,  7,  6,  5],
        [14, 13, 12, 11, 10],
        [19, 18, 17, 16, 15]],

       [[24, 23, 22, 21, 20],
        [29, 28, 27, 26, 25],
        [34, 33, 32, 31, 30],
        [39, 38, 37, 36, 35]],

       [[44, 43, 42, 41, 40],
        [49, 48, 47, 46, 45],
        [54, 53, 52, 51, 50],
        [59, 58, 57, 56, 55]]])

# Adding, Removing, Sorting elements

In [ ]:
#insert - add at index
first = np.array([1,2,3,4,5])
first = np.insert(first,3,6)
first

array([1, 2, 3, 6, 4, 5])

In [ ]:
#append - at the end
second = np.array([1,2,3,4])
second = np.append(second,6)
second

array([1, 2, 3, 4, 6])

In [ ]:
#delete - specify index
third = np.array([1,2,3,4,5])
third = np.delete(third,2)
third

array([1, 2, 4, 5])

In [ ]:
#sort - return a copy
four = np.random.randint(10,20,20)
four
np.sort(four)

array([10, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14, 15, 17, 17, 18, 18, 18,
       18, 18, 19])

In [ ]:
two_dim = np.random.randint(0,10,10).reshape((2,5))
two_dim

array([[4, 8, 8, 9, 7],
       [9, 4, 3, 0, 1]])

In [ ]:
np.sort(two_dim)

array([[4, 7, 8, 8, 9],
       [0, 1, 3, 4, 9]])

In [ ]:
#sort array of strings
str_arr = np.array(['red','white','blue','green','yellow','orange','saffron','black','magenta'])
str_arr

array(['red', 'white', 'blue', 'green', 'yellow', 'orange', 'saffron',
       'black', 'magenta'], dtype='<U7')

In [ ]:
np.sort(str_arr)

array(['black', 'blue', 'green', 'magenta', 'orange', 'red', 'saffron',
       'white', 'yellow'], dtype='<U7')

# Constant values arrays

In [ ]:
first_z_arr = np.zeros(5)
first_z_arr

array([0., 0., 0., 0., 0.])

In [ ]:
second_z_arr = np.zeros((4,5))
second_z_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
first_o_arr = np.ones(6)
first_o_arr

array([1., 1., 1., 1., 1., 1.])

In [ ]:
second_o_arr = np.ones((7,8))
second_o_arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
third_o_arr = np.ones((4,5), dtype=int)
third_o_arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

###Fill and Full

In [ ]:
fill_arr1=np.empty(10,dtype=int)
fill_arr1
fill_arr1.fill(12)
fill_arr1

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [ ]:
full_arr1 = np.full(5,10)
full_arr1

array([10, 10, 10, 10, 10])

In [ ]:
full_arr2 = np.full((4,5), 3)
full_arr2

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
 np.shape(full_arr2)

(4, 5)

In [ ]:
np.random.randint(0,4,(2,3))

array([[1, 1, 2],
       [3, 1, 1]])

#Joining

In [ ]:
arr_1 = np.arange(1,11)
arr_2 = np.arange(11,21)
print(arr_1)
print(arr_2)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


###Concatenate

In [ ]:
concat_arr = np.concatenate((arr_1, arr_2))
print(concat_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
arr_3_2d = np.arange(1, 11).reshape((2,5))
arr_3_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr_4_2d = np.arange(11, 21).reshape((2,5))
arr_4_2d

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
concat_arr_2d = np.concatenate((arr_3_2d, arr_4_2d),axis=1)
print(concat_arr_2d)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


###Stack

In [ ]:
stack_arr = np.stack((arr_1, arr_2), axis=0)
stack_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

###Horizontal and Vertical Stacking

In [ ]:
#horizontal
h_arr = np.hstack((arr_1, arr_2))
h_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#vertical
v_arr = np.vstack((arr_1, arr_2))
v_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

#Split

In [ ]:
#array_split
arr_5 = np.arange(1,13)
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
split_arr = np.array_split(arr_5,4)
split_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
split_arr[2]

array([7, 8, 9])

In [ ]:
#split unequally
np.array_split(arr_5,5)

[array([1, 2, 3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10]),
 array([11, 12])]

In [ ]:
arr_3_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#hsplit, equivalent to np.split(axis=1)
h_split = np.hsplit(arr_3_2d,5)
h_split

[array([[1],
        [6]]), array([[2],
        [7]]), array([[3],
        [8]]), array([[4],
        [9]]), array([[ 5],
        [10]])]

In [ ]:
arr_4_2d

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
#vertical split, equivalent to split(axis=0)
v_split = np.vsplit(arr_4_2d, 2)
v_split

[array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]

# Transpose, Move, Swap axis

In [ ]:
first_2d_arr = np.random.randint(1,11,12).reshape((3,4))
first_2d_arr

array([[10,  4,  1,  5],
       [ 4,  5, 10,  8],
       [ 6,  2,  1,  8]])

In [ ]:
np.transpose(first_2d_arr)

array([[10,  4,  6],
       [ 4,  5,  2],
       [ 1, 10,  1],
       [ 5,  8,  8]])

In [ ]:
second_2d_arr = np.random.randint(1,6,6).reshape((3,2))
second_2d_arr

array([[4, 5],
       [3, 5],
       [4, 2]])

In [ ]:
np.transpose(second_2d_arr,(1,0))

array([[4, 3, 4],
       [5, 5, 2]])

In [ ]:
#move axis

first_3d_arr = np.random.randint(1,11,24).reshape((2,3,4))
first_3d_arr

array([[[4, 1, 5, 4],
        [5, 8, 4, 6],
        [6, 2, 5, 4]],

       [[5, 7, 5, 3],
        [1, 4, 2, 1],
        [2, 2, 7, 4]]])

In [ ]:
np.moveaxis(first_3d_arr,-1,1)

array([[[4, 5, 6],
        [1, 8, 2],
        [5, 4, 5],
        [4, 6, 4]],

       [[5, 1, 2],
        [7, 4, 2],
        [5, 2, 7],
        [3, 1, 4]]])

In [ ]:
# swap axis

np.swapaxes(first_3d_arr,0,2)

array([[[4, 5],
        [5, 1],
        [6, 2]],

       [[1, 7],
        [8, 4],
        [2, 2]],

       [[5, 5],
        [4, 2],
        [5, 7]],

       [[4, 3],
        [6, 1],
        [4, 4]]])

In [ ]:
array_c = array_b.T
print(array_c)

[[1. 5.]
 [2. 6.]
 [3. 7.]
 [4. 8.]]


#Aggregate Functions

In [ ]:
 # set up data
 array_1 = np.array([[1,2], [3,4]])
 array_2 = np.array([[2,2], [6,6]])

In [ ]:
print(array_1.sum())

10


In [ ]:
print(array_1.sum(axis=0))
print(array_1.sum(axis=1))

[4 6]
[3 7]


In [ ]:
print(array_1.cumsum())

[ 1  3  6 10]


In [ ]:
print(array_1.prod())

24


In [ ]:
print(array_1.cumprod())

[ 1  2  6 24]


In [ ]:
#average
np.average(array_1)

2.5

# Array Math

### Two array math

In [ ]:
print(array_1)
print(array_2)

[[1 2]
 [3 4]]
[[2 2]
 [6 6]]


In [ ]:
print(array_1+array_2)

[[ 3  4]
 [ 9 10]]


In [ ]:
print(array_1-array_2)

[[-1  0]
 [-3 -2]]


In [ ]:
print(array_1*array_2)

[[ 2  4]
 [18 24]]


In [ ]:
print(array_1/array_2)

[[0.5        1.        ]
 [0.5        0.66666667]]


In [ ]:
print(np.dot(array_1, array_2))

[[14 14]
 [30 30]]


### 3x3 array math

In [ ]:
array_x = np.array([[1,2,3], [4,5,6],[7,8,9]])
array_y = np.array([[1,1,1], [2,2,2],[3,3,3]])

In [ ]:
print(array_x)
print(array_y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
print(array_x.sum(axis=0))

[12 15 18]


In [ ]:
print(array_x.ptp(axis=0))

[6 6 6]


In [ ]:
# point to point
print(array_x.ptp(axis=1))

[2 2 2]


In [ ]:
print(array_x.ptp())

8


In [ ]:
# min, max, mean, std
print(array_x.min(axis=0))
print(array_x.max(axis=0))
print(array_x.mean(axis=0))
print(array_x.std(axis=0))

[1 2 3]
[7 8 9]
[4. 5. 6.]
[2.44948974 2.44948974 2.44948974]


In [ ]:
# power
print(np.power(array_x, array_y))

[[  1   2   3]
 [ 16  25  36]
 [343 512 729]]


In [ ]:
array_z = np.array([[10,10,10], [20,20,20],[30,30,30]])

In [ ]:
print(array_z/array_x)

[[10.          5.          3.33333333]
 [ 5.          4.          3.33333333]
 [ 4.28571429  3.75        3.33333333]]


# Broadcasting

In [ ]:
array_1 = np.array([[1,1,1], [2,2,2], [3,3,3]])
print(array_1.shape)
array_2 = np.array([1,2,3])
print(array_2.shape)

(3, 3)
(3,)


In [ ]:
print(array_1+array_2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
array_1 = np.array([[1,1,1,1], [2,2,2,2], [3,3,3,3]])
print('Array 1:',array_1.shape)

array_2 = np.array([[1], [2], [3]])
print('Array 2:',array_2.shape)

Array 1: (3, 4)
Array 2: (3, 1)


In [ ]:
print(array_1*array_2)

[[1 1 1 1]
 [4 4 4 4]
 [9 9 9 9]]


In [ ]:
print(array_1.T)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
array_new = np.array([3,2,1])
print(array_1.T + array_new)

[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]


In [ ]:
print(array_1)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [ ]:
array_new2 = np.array([[1], [2], [3]])
print(array_new2)
print(array_1 + array_new2)

[[1]
 [2]
 [3]]
[[2 2 2 2]
 [4 4 4 4]
 [6 6 6 6]]


#Unique items and Frequency Counts

In [ ]:
first_arr = np.random.randint(1,11,20)
first_arr

array([ 5,  9,  1,  6,  1,  7,  5,  1,  6,  4,  2,  3,  2,  5, 10,  9,  4,
        4,  1, 10])

In [ ]:
np.unique(first_arr) #sorted

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10])

In [ ]:
second_arr = np.stack([[1,1,2,1], [2,4,0,4], [1,1,2,1], [1,4,1,4]])
second_arr

array([[1, 1, 2, 1],
       [2, 4, 0, 4],
       [1, 1, 2, 1],
       [1, 4, 1, 4]])

In [ ]:
np.unique(second_arr, axis=0)

array([[1, 1, 2, 1],
       [1, 4, 1, 4],
       [2, 4, 0, 4]])

In [ ]:
np.unique(second_arr, axis=1)

array([[1, 1, 2],
       [2, 4, 0],
       [1, 1, 2],
       [1, 4, 1]])

In [ ]:
#indices of unique elements

np.unique(second_arr,axis=0,return_index=True)

(array([[1, 1, 2, 1],
        [1, 4, 1, 4],
        [2, 4, 0, 4]]), array([0, 3, 1]))

In [ ]:
#frequency count

np.unique(second_arr,axis=1,return_counts=True)

(array([[1, 1, 2],
        [2, 4, 0],
        [1, 1, 2],
        [1, 4, 1]]), array([1, 2, 1]))

# Linear Algebra

In [ ]:
first_arr = np.arange(16).reshape(4,4)
first_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
first_matrix = np.matrix(first_arr)
first_matrix

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [ ]:
identity_matrix = np.matrix(np.identity(4))
identity_matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
#product
np.matmul(first_matrix, identity_matrix)

matrix([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [ ]:
#Inverse
c = np.matrix("0 1 2; 1 0 3; 4 -3 8")
c = np.linalg.inv(c)
c

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

# Solving Linear Equations

In [ ]:
a = np.mat("1 -2 1;0 2 -8;-4 5 9")
a

matrix([[ 1, -2,  1],
        [ 0,  2, -8],
        [-4,  5,  9]])

In [ ]:
b = np.array([0, 16, -18])
b

array([  0,  16, -18])

In [ ]:
print(np.linalg.solve(a,b))

[58. 32.  6.]


# Decomposition

In [ ]:
first_matrix = np.matrix([[4,8],[10,14]])
first_matrix

matrix([[ 4,  8],
        [10, 14]])

In [ ]:
evals, evec = np.linalg.eig(first_matrix)
print("Eigenvalues: \t", evals)
print("Eigenvectors: \t", evec)

Eigenvalues: 	 [-1.24695077 19.24695077]
Eigenvectors: 	 [[-0.83619408 -0.46462222]
 [ 0.54843365 -0.885509  ]]


In [ ]:
np.linalg.eigvals(first_matrix)

array([-1.24695077, 19.24695077])

#Singular Value Decomposition

In [ ]:
A = np.mat("3 1 4;1 5 9;2 6 5")
A

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [ ]:
U, sigma, V = np.linalg.svd(A, full_matrices=False)
print("U: \t",U)
print("Sigma: \t",sigma)
print("V: \t",V)

U: 	 [[-0.32463251  0.79898436  0.50619929]
 [-0.75307473  0.1054674  -0.64942672]
 [-0.57226932 -0.59203093  0.56745679]]
Sigma: 	 [13.58235799  2.84547726  2.32869289]
V: 	 [[-0.21141476 -0.55392606 -0.80527617]
 [ 0.46331722 -0.78224635  0.41644663]
 [ 0.86060499  0.28505536 -0.42202191]]


In [ ]:
U * np.diag(sigma) * V

matrix([[3., 1., 4.],
        [1., 5., 9.],
        [2., 6., 5.]])

#Polynomials

In [ ]:
from numpy.polynomial import polynomial

In [ ]:
first_poly = np.polynomial.Polynomial([2,-3,1])
first_poly

Polynomial([ 2., -3.,  1.], domain=[-1,  1], window=[-1,  1])

In [ ]:
second_poly = np.polynomial.Polynomial.fromroots([1,2])
second_poly

Polynomial([ 2., -3.,  1.], domain=[-1.,  1.], window=[-1.,  1.])

In [ ]:
first_poly.roots()

array([1., 2.])

In [ ]:
second_poly.roots()

array([1., 2.])

#y = x^4 + 2x^3 + 3x^2 + 4x + 5, x=1

In [ ]:
np.polyval([5,4,3,2,1],1)

15

In [ ]:
third_poly = np.polynomial.Polynomial([1,2,3,4,5])
third_poly

Polynomial([1., 2., 3., 4., 5.], domain=[-1,  1], window=[-1,  1])

In [ ]:
third_poly.integ()

Polynomial([0., 1., 1., 1., 1., 1.], domain=[-1.,  1.], window=[-1.,  1.])

In [ ]:
third_poly.integ().deriv()

Polynomial([1., 2., 3., 4., 5.], domain=[-1.,  1.], window=[-1.,  1.])

In [ ]:
third_poly.deriv()

Polynomial([ 2.,  6., 12., 20.], domain=[-1.,  1.], window=[-1.,  1.])

# Copy and Views

In [ ]:
students_id = np.array([111,122,133,144,155,166,177,188])
students_id

array([111, 122, 133, 144, 155, 166, 177, 188])

In [ ]:
student_reg = students_id
print("Students ID: ",id(students_id))
print("Students REG: ",id(student_reg))

Students ID:  140000327200656
Students REG:  140000327200656


In [ ]:
student_reg[1] = 221
print("Students ID: ",students_id)
print("Students REG: ",student_reg)

Students ID:  [111 221 133 144 155 166 177 188]
Students REG:  [111 221 133 144 155 166 177 188]


### Thus, assignemnts don't get copied

In [ ]:
students_id_copy = students_id.copy()
students_id_copy

array([111, 221, 133, 144, 155, 166, 177, 188])

In [ ]:
print(students_id_copy == students_id)

[ True  True  True  True  True  True  True  True]


In [ ]:
print("Students ID: ",id(students_id))
print("Students ID COPY: ",id(students_id_copy))

Students ID:  140000327200656
Students ID COPY:  140000326992688


In [ ]:
students_id[0]=100
print('Original: ', students_id)
print('Copy: ', students_id_copy)

Original:  [100 221 133 144 155 166 177 188]
Copy:  [111 221 133 144 155 166 177 188]


### Thus, the copy owns the data

In [ ]:
#view

students_id_view = students_id.view()

In [ ]:
students_id_view[0]=2000
print('Original', students_id)
print('View', students_id_view)

Original [2000  221  133  144  155  166  177  188]
View [2000  221  133  144  155  166  177  188]


In [ ]:
print(students_id_copy.base)
print(students_id_view.base)

None
[2000  221  133  144  155  166  177  188]


### Thus view does not own the data